# Generated by Django 4.2.23 on 2025-07-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('ambos', 'Ambos')], default='ambos', help_text='Define si el producto es de hombre, mujer o ambos.', max_length=10),
        ),
    ]
