# Generated by Django 4.2.23 on 2025-07-30 06:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='buyer_dni',
            field=models.CharField(default='', help_text='DNI del comprador', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='buyer_name',
            field=models.CharField(default='', help_text='Nombre completo del comprador', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='calle',
            field=models.CharField(default='', help_text='Calle de envío', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entre_calles',
            field=models.CharField(blank=True, default='', help_text='Referencia entre calles (opcional).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pago realizado'), ('REJECTED', 'Rechazado'), ('SHIPPED', 'Enviado')], default='PENDING', help_text='Estado actual del pedido.', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='localidad',
            field=models.CharField(default='', help_text='Localidad de envío', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='', help_text='Número de la dirección', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_method',
            field=models.CharField(choices=[('mp', 'Mercado Pago'), ('transferencia', 'Transferencia bancaria')], default='mp', help_text='Método de pago seleccionado.', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(default='', help_text='Provincia de envío', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de envío calculado.', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default='', help_text='Teléfono de contacto', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Número de seguimiento (cuando el pedido es enviado).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Suma de subtotales más envío.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el pedido (opcional; checkout sin login).', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='store.pedido')),
            ],
        ),
    ]
